package edu.asupoly.aspira.gui;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.AbstractListModel;

public class TimeDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public TimeDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }
    
    String[] getSelected()
    {
    	return selected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        TimesList = new javax.swing.JList();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TimesList.setModel(new AbstractListModel() {
        	String[] values = new String[] {"8:00 AM", "9:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM", "9:00 PM", "10:00 PM"};
        	public int getSize() {
        		return values.length;
        	}
        	public Object getElementAt(int index) {
        		return values[index];
        	}
        });
        TimesList.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        TimesList.setVisibleRowCount(-1);

        okButton.setText("Ok");
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                okButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(108)
        					.addComponent(okButton))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(TimesList, GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(TimesList, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(okButton)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void okButtonMousePressed(java.awt.event.MouseEvent evt) {                                      
        this.setVisible(false);
        selected = (String[])TimesList.getSelectedValues();
    }                                     

    
    // Variables declaration - do not modify                     
    private javax.swing.JList TimesList;
    private javax.swing.JButton okButton;
    String[] selected;
    // End of variables declaration                   
}
